name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Probar conexión con cPanel
        run: |
          RESPONSE=$(curl -s -k -H "cPanel-Token: cpanel ${{ secrets.CPANEL_TOKEN }}" \
            "https://server.mathe-comics.com:2083/execute/VersionControlDeployment/create?repository_root=/home/mathecomics/repositories/Mathecomics")
          echo "Respuesta de cPanel:"
          echo "$RESPONSE"
