name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel Git Deploy
        run: |
          curl -H "cPanel-Token: cpanel ${{ secrets.CPANEL_TOKEN }}" \
            "https://server.mathe-comics.com:2083/execute/VersionControl/update?repository_root=/home/mathecomics/repositories/Mathecomics&branch=main"
